# Generated by Django 3.2.24 on 2025-10-31 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address for sending invites', max_length=200, null=True)),
                ('joining', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('black_list', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=1)),
                ('access_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('invite_sent', models.BooleanField(default=False, help_text='Has this guest already been sent an invite?')),
                ('image', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, help_text='Base64 encoded QR code image', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
