# Generated by Django 2.2.4 on 2021-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210207_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referrals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referred_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
