# Generated by Django 2.2.4 on 2021-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pay_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
