# Generated by Django 2.2.4 on 2021-02-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
