# Generated by Django 2.2.4 on 2021-02-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210210_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profilePic',
            new_name='signature',
        ),
    ]
